import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>

<h1 style={{ color: 'blue', fontSize: '24px' }}>hello</h1>
      <Head>
      <Navbar />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 


    </>
  )
}